# -*- coding: utf-8 -*-
# Part A: answerable questions (retrieval + generation scored)
SPEC_A = [
# ---------------- admissions / prospective students ----------------
dict(id=0, lang="en", stratum="admissions",
 q="I got an offer for a master's at Trento and I'm from outside the EU. How much money do I need to show the embassy to get the student visa?",
 gold="At least €500 per month. The embassy asks for proof of adequate economic means of at least €500/month, along with the UniTrento admission letter, accommodation in Italy, health insurance and funds for the return trip.",
 obj="Single figure inside a bulleted list of visa requirements. The same page repeats '8 working days' and '90 days' figures, so a wrong number is easy to pick up.",
 url="https://www.unitn.it/en/international/coming-unitrento/all-you-need-know/visa",
 support="at least €500/month"),

dict(id=1, lang="en", stratum="admissions",
 q="Do I need an English certificate to get my study visa for 2026/27?",
 gold="Yes. From academic year 2026-2027, to apply for the visa you must submit to the Italian diplomatic representation an international certification attesting a B2 level of English in all four skills (speaking, writing, reading, listening), plus a CIMEA certificate of comparability and of verification of your final qualification (or a Declaration of Value from the same diplomatic representation).",
 obj="Conditional keyed to an academic year ('from 2026-2027'). Dropping the year condition, or dropping the CIMEA half, makes the answer wrong.",
 url="https://www.unitn.it/en/international/coming-unitrento/admission-how-it-works/admission-process",
 support="international certification attesting to a B2 level"),

dict(id=2, lang="it", stratum="admissions", flags=["cross_language"],
 q="Quanto mi costa vivere a Trento da studentessa? Soprattutto l'alloggio.",
 gold="Alloggio nelle residenze dell'Opera Universitaria: da 190 a 390 euro al mese, utenze incluse. Alloggio privato: da 300 a 700 euro al mese, utenze escluse. La pagina indica anche circa 150-200 euro al mese di spesa alimentare e 70 euro all'anno di abbonamento ai trasporti locali.",
 obj="Italian query against an English-only page (no Italian sibling in the corpus). Tests the query-translation path end to end.",
 url="https://www.unitn.it/en/international/coming-unitrento/all-you-need-know/cost-living",
 support="from €190 to €390 monthly"),

dict(id=3, lang="en", stratum="admissions",
 q="How long do I have to apply for my residence permit after I arrive in Italy?",
 gold="Within 8 working days of arrival you must submit the residence permit application to the Immigration Office. Non-EU citizens already residing in another EU country for study submit a declaration of presence instead, also within 8 working days.",
 obj="The '8 working days' figure appears three times on the page attached to three different procedures. Tests whether the right one is attached to the right case.",
 url="https://www.unitn.it/en/international/coming-unitrento/all-you-need-know/visa",
 support="within 8 working days of your arrival"),

dict(id=4, lang="en", stratum="admissions", flags=["stale_page","conflicting_sources"],
 q="When is the RIT admission test held?",
 gold="The RIT page in the corpus describes the 2025/26 round: the admission test was held online on 21 and 22 October 2025, applications closed on 13 October 2025 at 23:59 Italian time, and the Italian language test was on 29 October 2025. The same page labels the application option '...2026/2027', so the answer should state which edition the dates belong to rather than presenting them as current.",
 obj="effective_year 2025 page, so the recency weight penalises it, and the page contradicts itself on the edition year. Tests year-disambiguation (system prompt rule 11) rather than raw retrieval.",
 url="https://www.unitn.it/en/international/coming-unitrento/degree-seeking-student/rit-raise-your-international-talent-trento",
 support="21 and 22 October 2025"),

dict(id=5, lang="en", stratum="admissions",
 q="What score do I need in the RIT admission test to avoid paying tuition?",
 gold="Above 90/100 exempts you from tuition fees for the first year. Separately, the single highest-scoring candidate, if above 70/100, receives a scholarship for the first year; candidates scoring below 60/100 are not admitted.",
 obj="Three thresholds (60, 70, 90) with different consequences on one page. Tests whether the right threshold is matched to 'avoid paying tuition'.",
 url="https://www.unitn.it/en/international/coming-unitrento/degree-seeking-student/rit-raise-your-international-talent-trento",
 support="above 90/100 will be exempt"),

# ---------------- tuition ----------------
dict(id=6, lang="it", stratum="tuition",
 q="Ho un ISEE di 30.000 euro e mi iscrivo a una laurea magistrale. Quanto pago di tasse?",
 gold="Rientri nella fascia ISEE da 26.000,01 a 86.999,99 euro, per cui l'importo va da 367,00 a 3.345,00 euro (importo massimo per le lauree magistrali e le magistrali a ciclo unico di 6 anni). L'importo esatto si calcola con il simulatore tasse UniTrento.",
 obj="Two parallel band tables on one page, one for laurea/5-year single-cycle (max 2.384) and one for magistrale/6-year (max 3.345). Picking the wrong table gives a plausible wrong number.",
 url="https://www.unitn.it/it/studiare/tasse-borse-alloggi/tasse/cittadini-europei-ed-equivalenti",
 support="367,00 a € 3.345,00"),

dict(id=7, lang="it", stratum="tuition",
 q="Quando scadono le rate delle tasse?",
 gold="Per il 2026/2027: prima rata entro il 30 settembre 2026 se ti immatricoli a una laurea o a una magistrale a ciclo unico o se rinnovi l'iscrizione, mentre per la magistrale è entro 7 giorni dall'immatricolazione; seconda rata entro il 30 novembre 2026; terza rata entro il 31 marzo 2027.",
 obj="Branching answer: the first instalment deadline differs by course type. A flat '30 settembre' answer is incomplete.",
 url="https://www.unitn.it/it/studiare/tasse-borse-alloggi/tasse/rate-e-scadenze",
 support="3° rata: entro il"),

dict(id=8, lang="en", stratum="tuition",
 q="I paid an instalment two weeks after the deadline. How much is the late fee?",
 gold="40,00 euro, because the payment was more than 10 days after the due date. Within 10 days of the due date the charge is 12,00 euro.",
 obj="Requires applying a threshold ('two weeks' > 10 days) rather than copying a figure. Both figures sit adjacent on the page.",
 url="https://www.unitn.it/en/study/fees-scholarships-accommodation/tuition-fees/other-fees-and-costs",
 support="for more than 10 days after the due date"),

dict(id=9, lang="en", stratum="tuition",
 q="I only want to take one course, not a whole degree. What does that cost?",
 gold="Enrolment on a standard single course costs a minimum of 216,00 euro, which includes 6 CFU, plus 30,00 euro for each additional CFU. Single courses taken to integrate admission requirements or anticipate master's exams are priced differently: 200 euro up to 12 credits, 300 up to 24, 400 up to 36, 700 up to 60.",
 obj="Two different pricing schemes under one heading. A complete answer distinguishes them.",
 url="https://www.unitn.it/en/study/fees-scholarships-accommodation/tuition-fees/other-fees-and-costs",
 support="minimum fee of 216.00 euro"),

dict(id=10, lang="en", stratum="tuition",
 q="Can I pause my degree for a year, and does it cost anything?",
 gold="Not for a single year: the minimum interruption is 2 consecutive academic years, and the fee is 200,00 euro for each academic year of interruption.",
 obj="Counterintuitive constraint buried in a one-line section. The plausible default answer ('yes, 200 euro') is wrong on the year count.",
 url="https://www.unitn.it/en/study/fees-scholarships-accommodation/tuition-fees/other-fees-and-costs",
 support="minimum period of interruption is 2 consecutive academic years"),

dict(id=11, lang="en", stratum="tuition",
 q="How much is the student public transport pass?",
 gold="70,00 euro for the annual 'Libera circolazione' pass, valid from 1 September to 31 August of the following year.",
 obj="Plain fact retrieval; the same 70 euro figure also appears on the cost-of-living page, so both are acceptable sources.",
 url="https://www.unitn.it/en/study/fees-scholarships-accommodation/tuition-fees/other-fees-and-costs",
 support="from 1 September to 31 August of the following year"),

dict(id=12, lang="en", stratum="tuition", flags=["conflicting_sources"],
 q="What is the no-tax area ISEE threshold at UniTrento?",
 gold="The corpus does not agree with itself. Scholarship call annexes from 2026 state that 23.000 euro is the no-tax area threshold at UniTrento ('23.000 è la soglia no-tax area prevista in UniTrento'). The tuition page instead puts the lowest ISEE band at up to 26.000 euro, and that band is not zero: it runs from 146,00 to 366,00 euro. A good answer reports both figures with their sources rather than asserting one.",
 obj="Genuine cross-document contradiction. Tests system prompt rule 10 ('if sources disagree, say so and cite both') rather than fact lookup.",
 url="https://borse.unitn.it/system/files/allegati/1019/RET_222del16.03.2026%20-%20All.1.pdf",
 support="soglia no-tax area prevista in UniTrento"),

dict(id=13, lang="it", stratum="tuition",
 q="Devo iscrivermi all'esame di stato da ingegnere. Quanto devo pagare?",
 gold="Due voci: la tassa erariale di 49,58 euro all'Agenzia delle Entrate - Centro operativo di Pescara, e il contributo di iscrizione di 260 euro all'Università di Trento (sia per Ingegnere sezione A che per Ingegnere Iunior sezione B).",
 obj="Two-part answer; the 260 euro figure is shared by six professions listed together, so the model must not attach it to the wrong one or omit the tassa erariale.",
 url="https://www.unitn.it/it/studiare/dopo-lo-studio/esami-di-stato/tasse-e-contributi",
 support="49,58 euro"),

# ---------------- scholarships, incl. OCR sources ----------------
dict(id=14, lang="it", stratum="scholarship", flags=["ocr_source","about_other_institution"],
 q="C'è qualche premio di laurea per una tesi su temi ambientali a cui posso partecipare?",
 gold="Sì, il Premio ICU - Laura Conti (27ª edizione), pubblicato sul portale borse.unitn.it: primo premio 1.000 euro, secondo 500 euro, terzo 250 euro, con invio entro il 30 novembre 2026. Sono ammesse tesi di tutti i livelli, anche in lingua straniera, discusse in università italiane dall'anno accademico 2010-2011 in poi. Non è un premio dell'Università di Trento: è bandito dall'Ecoistituto/Fondazione ICU.",
 obj="OCR-recovered scan (tesseract) as the only source. Also an attribution test: the call is a third party's, merely hosted on a UniTrento portal.",
 url="https://borse.unitn.it/system/files/allegati/add/Bando%20Premio%20Laura%20Conti%202026.pdf",
 support="1.000 euro / 2"),

dict(id=15, lang="it", stratum="scholarship", flags=["ocr_source"],
 q="Quanto vale il premio del 'Bando Tesi 2026' pubblicato sulle borse UniTrento, e chi può partecipare?",
 gold="500,00 euro, un solo premio. Possono partecipare laureati da non più di 5 anni o laureandi di laurea di 1° o 2° livello, residenti in territorio italiano e iscritti presso qualunque università italiana, con una tesi in discipline umanistiche, scientifiche, economiche o sociali avente ad oggetto il territorio, la storia, la società o l'economia del Comune di San Salvatore Monferrato.",
 obj="OCR-recovered scan. Requires combining the prize amount (Art. 1/Art. 5) with the eligibility conditions (Art. 2) from different parts of the document.",
 url="https://borse.unitn.it/system/files/allegati/add/Bando%20Tesi%202026.pdf",
 support="1 premio da EURO 500,00"),

dict(id=16, lang="en", stratum="scholarship", flags=["ocr_source","about_other_institution"],
 q="Is the 500-euro thesis prize on the UniTrento scholarships site a University of Trento award?",
 gold="No. It is a competition run by the Comune di San Salvatore Monferrato (Province of Alessandria, Piedmont), which has awarded it annually since 2014; UniTrento only publishes the call on borse.unitn.it. Applications go to the Mayor of San Salvatore Monferrato, not to UniTrento.",
 obj="Attribution test on an OCR source. The failure mode is answering as if every document hosted on a unitn.it domain describes a UniTrento programme.",
 url="https://borse.unitn.it/system/files/allegati/add/Bando%20Tesi%202026.pdf",
 support="San Salvatore Monferrato ha istituito"),

dict(id=17, lang="it", stratum="scholarship", flags=["ocr_source","ocr_damage","source_error"],
 q="A quale indirizzo email va inviata la domanda per il Bando Tesi 2026 del Comune di San Salvatore Monferrato?",
 gold="Il documento, che è una scansione passata per OCR, riporta 'biblioteca@comune sansalvatoremonferrato.al.it' - manca il punto dopo 'comune', quindi l'indirizzo come stampato non è valido. La risposta corretta riporta quello che dice la fonte e segnala che il testo è danneggiato dall'OCR, invece di correggerlo silenziosamente o inventare un indirizzo plausibile.",
 obj="OCR damage, not source error: the scan mangles an email address. Faithful reproduction plus a flag is correct; silently repairing it to a guessed address is a fabrication.",
 url="https://borse.unitn.it/system/files/allegati/add/Bando%20Tesi%202026.pdf",
 support="biblioteca@comune sansalvatoremonferrato"),

dict(id=18, lang="it", stratum="scholarship", flags=["ocr_source"],
 q="Entro quando va consegnata la domanda per il bando tesi del Comune di San Salvatore Monferrato?",
 gold="Entro e non oltre le ore 12,00 del 30 novembre 2026.",
 obj="Precise deadline including the time of day, from an OCR'd scan. The corpus contains a second, unrelated call with the same 30 November 2026 date (Premio Laura Conti), so the two must not be merged.",
 url="https://borse.unitn.it/system/files/allegati/add/Bando%20Tesi%202026.pdf",
 support="ore 12,00 del 30 novembre 2026"),

dict(id=19, lang="en", stratum="scholarship", flags=["ocr_source","third_party_payment"],
 q="How do I pay the entry fee for the Laura Conti thesis prize?",
 gold="The call asks for 10 euro in administrative fees with the reference 'Premio ICU - L. Conti 2026', payable by postal account 29119880 to Ecoistituto del Veneto Alex Langer, by bank transfer to the IBAN printed in the call, or via the organiser's PayPal link. These are the organiser's payment details, not UniTrento's, and the answer should say so and point the student to the original call rather than presenting the bank details as official university instructions.",
 obj="Data-relay safety: the corpus contains third-party payment instructions on a unitn.it host. Tests whether the answer attributes them correctly instead of laundering them as university guidance.",
 url="https://borse.unitn.it/system/files/allegati/add/Bando%20Premio%20Laura%20Conti%202026.pdf",
 support="10 euro per spese di segreteria"),
]
