# -*- coding: utf-8 -*-
# Part B: coursecatalogue/syllabus, graduation, internship, services
SPEC_B = [
# ---------------- coursecatalogue / syllabus ----------------
dict(id=20, lang="en", stratum="syllabus",
 q="How many credits is Educational technology in the Human-Computer Interaction master, and who teaches it?",
 gold="6 ECTS, taught by Daniele Agostini. It is SSD INFO-01/A, delivered in English in the first semester.",
 obj="The whole answer sits in the one-line metadata header the coursecatalogue API emits. Tests whether that header survives chunking and is retrievable at all.",
 url="https://unitn.coursecatalogue.cineca.it/corsi/2026/10859/insegnamenti/2026/51297_652930_94002/2026/51297?coorte=2026&schemaid=9588&lang=en",
 support="Educational technology - HUMAN-COMPUTER INTERACTION (Department of Psychology", also=["https://unitn.coursecatalogue.cineca.it/corsi/2026/10859/insegnamenti/2026/51297_652930_94002/2026/51297?coorte=2026&schemaid=9588&lang=it"]),

dict(id=21, lang="en", stratum="syllabus",
 q="How much of Educational technology is online rather than in class?",
 gold="Of 42 scheduled hours, 28 are face-to-face and 14 are asynchronous online. There are no scheduled synchronous online hours, and the 14 online hours are designed as native asynchronous activities on Moodle, not recordings of lectures.",
 obj="Three numbers that must be kept apart (42 total, 28 in class, 14 online) plus an explicit negative ('no synchronous hours'). The per-module breakdown repeats similar numbers six times immediately after.",
 url="https://unitn.coursecatalogue.cineca.it/corsi/2026/10859/insegnamenti/2026/51297_652930_94002/2026/51297?coorte=2026&schemaid=9588&lang=en",
 support="28 hours of face-to-face learning and 14 hours of asynchronous"),

dict(id=22, lang="en", stratum="syllabus",
 q="I have no coding background. Can I take Educational technology?",
 gold="Yes. No specialised programming background and no previous knowledge of Educational Technology are required; you need to be comfortable with computers or mobile devices, the internet, presentation and document software and online learning environments, and able to study in English.",
 obj="Negative fact ('no programming required') in a Prerequisites section. Answering 'you should check' or hedging is a failure; so is inventing a prerequisite.",
 url="https://unitn.coursecatalogue.cineca.it/corsi/2026/10859/insegnamenti/2026/51297_652930_94002/2026/51297?coorte=2026&schemaid=9588&lang=en",
 support="No specialised programming background"),

dict(id=23, lang="en", stratum="syllabus", flags=["conflicting_sources","intra_document_conflict"],
 q="How is Educational technology assessed - is it a written exam?",
 gold="The page disagrees with itself. The metadata header records the assessment as 'Scritto (Final grade)', i.e. written, while the syllabus body describes a group project (groups of no more than four), a portfolio, peer review and an individual oral defence. A good answer reports both and does not silently pick one.",
 obj="Contradiction inside a single document, between the structured header the API emits and the free-text body. Tests rule 10 at intra-document scale, where 'cite both sources' has only one source to cite.",
 url="https://unitn.coursecatalogue.cineca.it/corsi/2026/10859/insegnamenti/2026/51297_652930_94002/2026/51297?coorte=2026&schemaid=9588&lang=en",
 support="individual oral defence"),

dict(id=24, lang="it", stratum="syllabus", flags=["bilingual_pair"],
 q="Quanti CFU vale Educational technology nel corso di Human-Computer Interaction?",
 gold="6 CFU, SSD INFO-01/A, insegnamento in inglese al primo semestre, docente Daniele Agostini.",
 obj="Italian sibling of id 20. Both the IT and EN catalogue pages are in the index and both are correct answers, so this is the hit_at_k bilingual false-negative case the eval doc flagged: acceptable_urls must hold both.",
 url="https://unitn.coursecatalogue.cineca.it/corsi/2026/10859/insegnamenti/2026/51297_652930_94002/2026/51297?coorte=2026&schemaid=9588&lang=it",
 support="Educational technology - HUMAN-COMPUTER INTERACTION (Dipartimento di Psicologia", also=["https://unitn.coursecatalogue.cineca.it/corsi/2026/10859/insegnamenti/2026/51297_652930_94002/2026/51297?coorte=2026&schemaid=9588&lang=en"]),

dict(id=25, lang="en", stratum="syllabus", flags=["near_duplicate","counterintuitive"],
 q="Semiotics of art is in the English course catalogue. Is the course taught in English?",
 gold="No, it is taught in Italian (6 ECTS, SSD PHIL-04/A, first semester) even though its catalogue entry is available in English. The same course appears under two master's programmes, Philosophy and Languages of Modernity and History of Art and Museum Studies, with identical metadata.",
 obj="Two near-identical catalogue pages for one course under different degrees - the family_cap crowding pattern. Also a counterintuitive fact: an English catalogue page for an Italian-taught course.",
 url="https://unitn.coursecatalogue.cineca.it/corsi/2026/10837/insegnamenti/2026/51271_656153_96345/2026/51271?coorte=2026&schemaid=9532&lang=en",
 support="Semiotics of art", url_must_match=r"coursecatalogue"),

dict(id=26, lang="en", stratum="syllabus", flags=["temporal","near_duplicate","disambiguation"],
 q="What's the syllabus of Introduction to Economics for surnames A-K?",
 gold="The catalogue holds this course for several academic years (2022/23 through 2026/27) and under more than one degree programme (Accounting and Law, Business Administration, Business Administration and Law). A correct answer names the academic year and degree programme it is describing, or asks which one is meant, rather than blending editions.",
 obj="Worst case for family_cap and recency together: 15+ near-identical siblings differing only by year and degree. Scored on whether the answer scopes itself, not on which edition it picks.",
 url="https://unitn.coursecatalogue.cineca.it/corsi/2026/10856/insegnamenti/2026/120004%2F1-AK/2026/51261?coorte=2026&schemaid=9492&adCodFraz=120004&lang=en",
 support="Introduction to Economics (Surname beginning with A-K)", max_urls=25),

# ---------------- graduation ----------------
dict(id=27, lang="en", stratum="graduation", flags=["temporal","disambiguation"],
 q="When is the next graduation session for the Data Science master's and when do I have to apply?",
 gold="For the 2026 sessions listed: dissertation topic by 15 May 2026, graduation application from 15 June to 17 July 2026 at 12.00, thesis upload from 15 June to 28 August 2026, graduation on 15 and 16 September 2026. The page also lists the earlier 2026 session (topic by 3 March, application 4-29 May, graduation 30 June-1 July 2026) and a full set of 2025 dates, so the answer must say which session it is quoting.",
 obj="Two tables on one page, one per academic year, exactly the #23-style multi-year crowding already documented in the generation audit. Scored on whether one session is picked and labelled.",
 url="https://corsi.unitn.it/en/data-science/graduation/graduation-calendar",
 support="15 and 16 September 2026"),

dict(id=28, lang="en", stratum="graduation", flags=["source_error"],
 q="What is the thesis upload deadline for the September 2026 Data Science graduation session?",
 gold="The page prints 'from 15 June to 28 August September 2026 at 12.00' - a typo in the source, which names two months. The correct behaviour is to report the range as printed and flag that the source is ambiguous, not to silently choose August or September.",
 obj="Planted-style source error that is genuinely in the corpus. Faithful reproduction plus a flag is correct; silently resolving it is a fabrication. Compare v4 #8 and #14.",
 url="https://corsi.unitn.it/en/data-science/graduation/graduation-calendar",
 support="28 August September 2026"),

dict(id=29, lang="en", stratum="graduation",
 q="Does my master's thesis in Physics have to be written in English?",
 gold="Yes. Both the thesis and its discussion must be in English for the Master's degree in Physics.",
 obj="Short, unambiguous fact on a small page (1,588 chars) that competes with a dozen sibling 'final exam' pages from other degree programmes.",
 url="https://corsi.unitn.it/en/physics-master/graduation/final-exam",
 support="Both the thesis and its discussion must be in"),

dict(id=30, lang="en", stratum="graduation", flags=["cross_language","temporal"],
 q="What is the maximum number of exams in the Physics master's degree?",
 gold="12, in addition to the 'altre' training activities and the final exam, under art. 4 comma 2 of DM 1649/2023. This is stated in the 2025 regolamento didattico of the LM in Fisica.",
 obj="English query against an Italian-only PDF, and the fact exists only in the 2025 edition - the 2020 edition of the same regolamento is also in the corpus and does not contain it. Tests translation plus edition selection together.",
 url="https://corsi.unitn.it/sites/cds/files/2026-02/regolamento-didattico-lm-fisica-2025.pdf",
 support="numero massimo di esami previsti nel CdS"),

dict(id=31, lang="it", stratum="graduation",
 q="Quanti appelli d'esame all'anno sono garantiti nella magistrale in Fisica?",
 gold="Almeno cinque all'anno, distribuiti nelle sessioni di gennaio-febbraio, giugno-luglio e agosto-settembre, al di fuori dei periodi di lezione.",
 obj="Fact inside a long Italian PDF (36,908 chars), so it depends on the right chunk surfacing, not just the right document.",
 url="https://corsi.unitn.it/sites/cds/files/2026-02/regolamento-didattico-lm-fisica-2025.pdf",
 support="almeno cinque all'anno", url_must_match=r"lm-fisica"),

dict(id=32, lang="en", stratum="graduation", flags=["cross_language","old_document","counterintuitive"],
 q="Does my bachelor's thesis in Physics have to be original research?",
 gold="No. The regolamento didattico states the elaborato does not necessarily have to be original ('non deve necessariamente presentare caratteristiche di originalità'); it is an occasion to show you can present and discuss a physics topic clearly and competently. The final exam consists of a written elaborato and a colloquium.",
 obj="The supporting document is the 2021 edition (effective_year 2024), so recency_weight actively penalises the only page that answers the question. Counterintuitive negative fact whose plausible default answer is 'yes'.",
 url="https://corsi.unitn.it/sites/cds/files/2024-12/regolamento-didattico-l-fisica-2021.pdf",
 support="non deve necessariamente presentare caratteristiche di originalit"),

# ---------------- internship ----------------
dict(id=33, lang="en", stratum="internship",
 q="How many hours is the internship in the Data Science master's, and how many credits do I get?",
 gold="At least 225 hours for 9 ECTS, to be completed within no more than 12 months. Longer internships earn extra credits at 1 credit per additional 25 hours, up to a maximum of 10 credits in total.",
 obj="Nine or more degree programmes have an 'Internship' page at the same URL depth with different figures - the sibling-crowding failure (#38 in v4). Tests whether the right programme's page wins.",
 url="https://corsi.unitn.it/en/data-science/study/internship",
 support="at least 225 total hours"),

dict(id=34, lang="en", stratum="internship", flags=["sibling_distractor"],
 q="How many credits is the internship in Cognitive Science and when can I start it?",
 gold="15 ECTS for 375 hours of activity. You must be enrolled in the second year and have gained at least 45 credits before the internship begins, and the project must be supervised by a CIMeC tutor or an equivalent profile.",
 obj="Deliberate pair with id 33: same question shape, different programme, very different numbers (15/375 vs 9/225). Answering one with the other's figures is the specific failure being measured.",
 url="https://corsi.unitn.it/en/cognitive-science/study/internship",
 support="375 hours of activity"),

dict(id=35, lang="en", stratum="internship", flags=["counterintuitive"],
 q="Is the internship compulsory in the Data Science master's?",
 gold="No. The internship is not mandatory; it can substitute the 'Work-oriented activities' in the second year.",
 obj="Negative fact. The plausible default is 'yes', and several sibling programmes do make it compulsory, so a crowded context pushes towards the wrong answer.",
 url="https://corsi.unitn.it/en/data-science/study/internship",
 support="is not mandatory and can substitute"),

# ---------------- services ----------------
dict(id=36, lang="en", stratum="services",
 q="My study plan has classes in a computer lab. What safety training do I need to do?",
 gold="Two courses: General safety training (4 hours, online self-study, certificate and a non-expiring Open Digital Badge), then Specific safety training - Low Risk (4 hours, online self-study), which is mandatory for students whose study plan includes classes in computer laboratories. You must pass the general course before taking the low-risk final test; the low-risk badge is valid for 5 years.",
 obj="Requires composing a prerequisite chain across two sections and picking Low Risk rather than Medium Risk. Both sections repeat '4 hours' and 'online self-study'.",
 url="https://www.unitn.it/en/study/register/documents-and-certificates/safety-training",
 support="have classes in computer laboratories"),

dict(id=37, lang="en", stratum="services",
 q="Can I do the medium risk safety course online whenever I want?",
 gold="No. Medium Risk is delivered live on Zoom in classes of at most 35 participants, lasts 8 hours and requires at least 90% attendance; you choose a date from the calendar. Only General and Low Risk are online self-study courses.",
 obj="Negative answer that requires contrasting one section against the two adjacent ones, all of which say 'online self-study'.",
 url="https://www.unitn.it/en/study/register/documents-and-certificates/safety-training",
 support="8 hours with at least 90% attendance"),

dict(id=38, lang="en", stratum="services",
 q="I'm a non-EU student. How much does it cost to register with the Italian national health service, and can I add my family?",
 gold="700,00 euro per year, with coverage valid from activation until 31 December of that year. To extend coverage to family members: 1.300,00 euro extra if you have already paid the 700 euro, or 2.000,00 euro if you have not yet joined. The amount is higher if you had employment income in the previous year.",
 obj="Three figures with different conditions attached, plus a validity date that is easy to drop. The 700 euro figure also appears on the cost-of-living page and in the EU PhD student paragraph of the same page under different conditions.",
 url="https://www.unitn.it/en/international/coming-unitrento/all-you-need-know/health-insurance",
 support="700.00 euro per year"),

dict(id=39, lang="en", stratum="services",
 q="I saw a doctor who isn't on the university's list. Can I get reimbursed?",
 gold="You pay the visit yourself - 20,00 euro for an outpatient visit, 35,00 euro for a home visit - keep the receipt, and then request reimbursement from the Ufficio Prestazioni of the APSS of the practitioner you consulted, or from the health service of your region of residence if you are an Italian student.",
 obj="Conditional procedure with two figures. The same page lists ten physicians with phone numbers, which is strong distractor material for a 'doctor' query.",
 url="https://www.unitn.it/en/study/services/student-benefits/healthcare",
 support="for an outpatient visit"),

dict(id=40, lang="en", stratum="services",
 q="I have a specific learning disorder and need extra time for the CLA placement test. How do I request it?",
 gold="Email esamicla@unitn.it stating which language test you intend to take (English, French, German, Spanish, Italian or Russian), at least 5 working days before the date you plan to take the test.",
 obj="Three-part answer (address, content, notice period). The page also states a different 5-working-day window for external users receiving CLA access instructions, which is a direct distractor.",
 url="https://www.cla.unitn.it/en/home/placement-test",
 support="at least 5 working days before the date"),

dict(id=41, lang="en", stratum="services",
 q="How long is the CLA placement test and do wrong answers cost me points?",
 gold="It never lasts more than 50 minutes (the exact time depends on the language, and a timer is shown). Wrong answers do deduct points; unanswered questions score 0 and correct answers score a positive value indicated next to each question.",
 obj="Two-part answer including a scoring rule expressed as a negative. The test is also not available for Chinese, Portuguese and Arabic, which a complete answer may mention.",
 url="https://www.cla.unitn.it/en/home/placement-test",
 support="it does not last more than 50 minutes"),

dict(id=42, lang="it", stratum="services",
 q="Quando escono i bandi per le 150 ore?",
 gold="Di solito nella prima metà di settembre. Le informazioni complete sono sulla pagina del Service Desk, accessibile solo dopo il login con le credenziali di Ateneo.",
 obj="Very short page (835 chars) close to the loader's min_chars floor, competing with a 12,766-char 'Paid student work' hub page and a safety-training page that both mention '150 ore'.",
 url="https://www.unitn.it/it/studiare/collabora-con-noi/150-ore",
 support="prima metà di settembre", url_must_match=r"150-ore"),

dict(id=43, lang="en", stratum="services",
 q="If I withdraw from my studies, do I have to pay anything first?",
 gold="Yes: the online withdrawal application requires a 16 euro stamp duty, and it is accepted only if your enrolment is in order. That means the first instalment paid if you apply by 30 November, the first and second (if your ISEE requires the second) by 31 March, and all instalments if you apply after 31 March.",
 obj="Conditional ladder keyed to three dates. The v4 audit found repeated failures where the model drops a conditional qualifier (#11, #33); this is the same shape.",
 url="https://www.unitn.it/en/study/enrol/suspensions-and-withdrawals/withdrawal-studies",
 support="payment of a 16 euro stamp duty"),

dict(id=44, lang="it", stratum="services",
 q="Chi gestisce le mense universitarie a Trento?",
 gold="L'Opera Universitaria, attraverso mense e bar in città e in collina a Trento, e locali convenzionati a Rovereto e San Michele all'Adige. Vi possono accedere anche studenti e studentesse dei corsi sanitari immatricolati all'Università di Verona.",
 obj="591-char page, the shortest target in the set - a chunking/min_chars edge case. The Verona detail is a counterintuitive addition that tests whether the whole short page is used.",
 url="https://www.unitn.it/it/studiare/servizi/mense",
 support="corsi sanitari immatricolati all"),

dict(id=45, lang="en", stratum="admissions", flags=["about_other_institution"],
 q="What tuition do I pay for the double degree with Tilburg University?",
 gold="The Tilburg factsheet in the corpus describes a combination of a Trento admin fee, Tilburg's statutory rate and the Trento tuition fee, varying by category and year - these are the dual-degree arrangement's terms, and the accompanying DL_TILBURG_TuitionFees_and_StudyPlan.pdf extracted as unreadable glyph codes, so it cannot be quoted. UniTrento's own fees still follow the ISEE bands on the tuition page. A good answer distinguishes what Tilburg charges from what UniTrento charges and points to the programme office rather than stating a single figure.",
 obj="Partner-institution document that the eval-set doc already flagged as a trap, plus a genuinely broken extraction (the tuition PDF's text is glyph indices, not words). Tests whether an unreadable source is recognised as unusable.",
 url="https://www.unitn.it/sites/default/files/2025-01/DL_Tilburg_Factsheet_2025-26.pdf",
 support="Trento admin fee"),

dict(id=46, lang="en", stratum="admissions", flags=["about_other_institution"],
 q="What's the minimum GPA Trento requires for a master's?",
 gold="UniTrento does not use GPA; admission requirements are set per course, for example a weighted average of at least 22/30 for the master's in Environmental Engineering, with a review and interview for averages between 22 and 24. The corpus contains DL_CEAS_FAQ.pdf, which asks and answers a minimum-GPA question, but that document is the University of Cincinnati's and links to grad.uc.edu - it must not be used to answer for Trento.",
 obj="The single strongest lexical match for 'minimum GPA' in the corpus is a partner institution's FAQ. Tests whether host domain is mistaken for authorship.",
 url="https://corsi.unitn.it/it/ingegneria-lambiente-e-il-territorio-magistrale/iscriversi/ammissione-europei-e-equivalenti",
 support="22/30 e 24/30",
 distractor_url="https://www.unitn.it/sites/default/files/2024-10/DL_CEAS_FAQ.pdf"),
]
